version: "3"

services:
    client:
        image: nginx
        ports:
            - 8000:80
        volumes:
            - ./src:/usr/share/nginx/html:ro
        networks:
            testing_net:
                ipv4_address:  172.28.1.1

    web2:
        image: nginx
        ports:
            - 8080:80
        volumes:
            - ./node2:/usr/share/nginx/html:ro        
        networks:
          testing_net:
                ipv4_address:  172.28.1.2

    mycli:
        image: ubuntu
        command: tail -F anything
        volumes:
            - ./node2:/usr/share/nginx/html:ro        
        networks:
          testing_net:
                ipv4_address:  172.28.1.3            

networks:
    testing_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16            